<?php

/**
 * This is the model base class for the table "igu_district".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IguDistrict".
 *
 * Columns in table "igu_district" available as properties of the model,
 * followed by relations of table "igu_district" available as properties of the model.
 *
 * @property integer $id
 * @property string $district
 * @property integer $idprovince
 *
 * @property IguAgents[] $iguAgents
 * @property IguProvince $idprovince0
 * @property IguRegistration[] $iguRegistrations
 */
abstract class BaseIguDistrict extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'igu_district';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Akarere|Akarere', $n);
	}

	public static function representingColumn() {
		return 'district';
	}

	public function rules() {
		return array(
			array('district, idprovince', 'required'),
			array('district', 'unique'),
			array('idprovince', 'numerical', 'integerOnly'=>true),
			array('district', 'length', 'max'=>20),
			array('id, district, idprovince', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'iguAgents' => array(self::HAS_MANY, 'IguAgents', 'iddistrict'),
			'idprovince0' => array(self::BELONGS_TO, 'IguProvince', 'idprovince'),
			'iguRegistrations' => array(self::HAS_MANY, 'IguRegistration', 'iddistrict'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'district' => Yii::t('app', 'Akarere'),
			'idprovince' => null,
			'iguAgents' => null,
			'idprovince0' => null,
			'iguRegistrations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('district', $this->district, true);
		$criteria->compare('idprovince', $this->idprovince);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}