<?php

/**
 * This is the model base class for the table "igu_companytype".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IguCompanytype".
 *
 * Columns in table "igu_companytype" available as properties of the model,
 * followed by relations of table "igu_companytype" available as properties of the model.
 *
 * @property integer $id
 * @property string $companytype
 *
 * @property IguRegistration[] $iguRegistrations
 */
abstract class BaseIguCompanytype extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'igu_companytype';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ubwoko bw Ikigo|Ubwoko bw Ikigo', $n);
	}

	public static function representingColumn() {
		return 'companytype';
	}

	public function rules() {
		return array(
			array('companytype', 'required'),
			array('companytype', 'length', 'max'=>20),
			array('id, companytype', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'iguRegistrations' => array(self::HAS_MANY, 'IguRegistration', 'idcompanytype'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'companytype' => Yii::t('app', 'Ubwoko bw Ikigo'),
			'iguRegistrations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('companytype', $this->companytype, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}