<?php

/**
 * This is the model base class for the table "igu_credit".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IguCredit".
 *
 * Columns in table "igu_credit" available as properties of the model,
 * followed by relations of table "igu_credit" available as properties of the model.
 *
 * @property integer $id
 * @property integer $cash
 * @property integer $days
 *
 * @property IguVoucher[] $iguVouchers
 */
abstract class BaseIguCredit extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'igu_credit';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IguCredit|IguCredits', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('cash, days', 'required'),
			array('cash, days', 'numerical', 'integerOnly'=>true),
			array('id, cash, days', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'iguVouchers' => array(self::HAS_MANY, 'IguVoucher', 'idcredit'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'cash' => Yii::t('app', 'Cash'),
			'days' => Yii::t('app', 'Days'),
			'iguVouchers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('cash', $this->cash);
		$criteria->compare('days', $this->days);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}