<?php

/**
 * This is the model base class for the table "igu_investment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IguInvestment".
 *
 * Columns in table "igu_investment" available as properties of the model,
 * followed by relations of table "igu_investment" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idclient
 * @property integer $idproduct
 * @property integer $cashinvested
 * @property integer $cashprofit
 * @property integer $year
 *
 * @property IguRegistration $idclient0
 */
abstract class BaseIguInvestment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'igu_investment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IguInvestment|IguInvestments', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('idclient, idproduct, cashinvested, cashprofit, year', 'required'),
			array('idclient, idproduct, cashinvested, cashprofit, year', 'numerical', 'integerOnly'=>true),
			array('id, idclient, idproduct, cashinvested, cashprofit, year', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idclient0' => array(self::BELONGS_TO, 'IguRegistration', 'idclient'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idclient' => null,
			'idproduct' => Yii::t('app', 'Idproduct'),
			'cashinvested' => Yii::t('app', 'Cashinvested'),
			'cashprofit' => Yii::t('app', 'Cashprofit'),
			'year' => Yii::t('app', 'Year'),
			'idclient0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idclient', $this->idclient);
		$criteria->compare('idproduct', $this->idproduct);
		$criteria->compare('cashinvested', $this->cashinvested);
		$criteria->compare('cashprofit', $this->cashprofit);
		$criteria->compare('year', $this->year);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}