<?php

/**
 * This is the model base class for the table "igu_province".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IguProvince".
 *
 * Columns in table "igu_province" available as properties of the model,
 * followed by relations of table "igu_province" available as properties of the model.
 *
 * @property integer $id
 * @property string $province
 *
 * @property IguDistrict[] $iguDistricts
 */
abstract class BaseIguProvince extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'igu_province';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Intara|Intara', $n);
	}

	public static function representingColumn() {
		return 'province';
	}

	public function rules() {
		return array(
			array('province', 'required'),
			array('province', 'length', 'max'=>30),
			array('id, province', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'iguDistricts' => array(self::HAS_MANY, 'IguDistrict', 'idprovince'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'province' => Yii::t('app', 'Intara'),
			'iguDistricts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('province', $this->province, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}