<?php

/**
 * This is the model base class for the table "igu_image_product".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IguImageProduct".
 *
 * Columns in table "igu_image_product" available as properties of the model,
 * followed by relations of table "igu_image_product" available as properties of the model.
 *
 * @property integer $id
 * @property string $image
 * @property integer $idclientproduct
 *
 * @property IguClientProduct $idclientproduct0
 */
abstract class BaseIguImageProduct extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'igu_image_product';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IguImageProduct|IguImageProducts', $n);
	}

	public static function representingColumn() {
		return 'image';
	}

	public function rules() {
		return array(
			array('idclientproduct', 'required'),
			array('idclientproduct', 'numerical', 'integerOnly'=>true),
			array('image', 'length', 'max'=>100),
			array('id, image, idclientproduct', 'safe', 'on'=>'search'),
			array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
			array('image', 'length', 'max'=>255, 'on'=>'insert,update'),
		);
	}

	public function relations() {
		return array(
			'idclientproduct0' => array(self::BELONGS_TO, 'IguClientProduct', 'idclientproduct'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'image' => Yii::t('app', 'Ifoto'),
			'idclientproduct' => null,
			'idclientproduct0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('idclientproduct', $this->idclientproduct);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}