/*
 * File: app/controller/Products.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inyungu.controller.Products', {
    extend: 'Ext.app.Controller',

    config: {
        stores: [
            'Products'
        ],

        refs: {
            dataList: '#dataList',
            mainNav: {
                autoCreate: true,
                selector: '#mainnav',
                xtype: 'mainnav'
            },
            detailCard: 'detailpanel'
        },

        control: {
            "list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var info,details;

            if (record) {
               details = Ext.create('Inyungu.view.DetailPanel', {
                    title: 'Ibicuruzwa'
                });


                // set the info
                info = details.child('#contact').child('#info');
                info.child('#photo').setData(record.data);
                info.child('#data').setData(record.data);


                this.getMainNav().push(details);
            }
    }

});