/*
 * File: app/store/Products.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inyungu.store.Products', {
    extend: 'Ext.data.Store',

    requires: [
        'Inyungu.model.Product',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json',
        'Ext.util.Grouper'
    ],

    config: {
        autoLoad: true,
        model: 'Inyungu.model.Product',
        storeId: 'Products',
        proxy: {
            type: 'jsonp',
            url: 'http://127.0.0.1/inyungu/index.php?r=sencha',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        grouper: {
            property: 'creationedat'
        }
    }
});