/*
 * File: app/view/ListContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inyungu.view.ListContainer', {
    extend: 'Ext.Container',
    alias: 'widget.listcontainer',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.field.Search'
    ],

    config: {
        fullscreen: true,
        layout: 'fit',
        items: [
            {
                xtype: 'list',
                cls: 'tpl-ahnatkat',
                id: 'dataList',
                itemTpl: [
                    '<div >',
                    '<img class="photo" src="images/{image}" width="40" height="40"/>',
                    '{productname} <span class=\'datepos\'>{creationdate}</span>',
                    '<br/>',
                    '    <small class=\'textpos\'>{quantity}{mesure},{currentprice}frw/1,{telephone},{district}</small>',
                    '</div>',
                    '',
                    '<div style=\'display:none\'>{umurenge}{akagali}{intara}</div>'
                ],
                store: 'Products',
                grouped: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'searchfield',
                                itemId: 'searchField',
                                autoComplete: false
                            }
                        ]
                    }
                ]
            }
        ]
    }

});